export interface PhoneItem {
  id: string;
  price: number;
  title: string;
  brand: string;
  ram?: string;
  storage: string;
  battery?: string;
  color?: string;
  description: string;
  image: string;
  alt: string;
  link: string;
}

export interface PhoneData {
  brand: string;
  models: PhoneItem[];
}

export const phonesData: PhoneData[] = [
  {
    brand: "Apple",
    models: [
      {
        id: "iphone-1",
        title: "iPhone XR",
        description:
          "Pantalla Liquid Retina 6.1'', cámara simple 12MP, chip A12 Bionic, Face ID, batería para todo el día.",
        image: "/images/imagenes_de_celulares/iphoneXr.jpeg",
        price: 350000,
        storage: "64GB",
        battery: "90%",
        color: "black",
        brand: "Apple",
        alt: "iPhone XR",
        link: "#",
      },
      {
        id: "iphone-2",
        title: "iPhone 11",
        description:
          "Pantalla Liquid Retina 6.1'', cámara dual 12MP, chip A13 Bionic, Face ID, batería mejorada.",
        image: "/images/imagenes_de_celulares/iphone11lila.jpeg",
        price: 450000,
        storage: "128GB",
        battery: "95%",
        color: "purple",
        brand: "Apple",
        alt: "iPhone 11",
        link: "#",
      },
      {
        id: "iphone-3",
        title: "iPhone 12",
        description:
          "Pantalla OLED Super Retina XDR 6.1'', cámara dual 12MP, chip A14 Bionic, 5G, diseño compacto.",
        image:"/images/imagenes_de_celulares/iphone12.jpeg",
        price: 650000,
        storage: "128GB",
        battery: "92%",
        color: "black",
        brand: "Apple",
        alt: "iPhone 12",
        link: "#",
      },
      {
        id: "iphone-4",
        title: "iPhone 12pro-Max",
        description:
          "Pantalla OLED Super Retina XDR 6.1'', cámara dual 12MP, chip A14 Bionic, 5G, diseño compacto.",
        image: "/images/imagenes_de_celulares/iphone12pro.jpeg",
        price: 700000,
        storage: "128GB",
        battery: "100%",
        color: "white",
        brand: "Apple",
        alt: "iPhone 12proMax",
        link: "#",
      },
      {
        id: "iphone-5",
        title: "iPhone 13",
        description:
          "Pantalla OLED Super Retina XDR 6.1'', cámara dual 12MP con estabilización óptica, chip A15 Bionic, 5G.",
        image: "/images/imagenes_de_celulares/iphone13.jpeg",
        price: 690000,
        storage: "128GB",
        battery: "100%",
        color: "white",
        brand: "Apple",
        alt: "iPhone 13",
        link: "#",
      },
      {
        id: "iphone-6",
        title: "iPhone 13",
        description:
          "Pantalla OLED Super Retina XDR 6.1'', cámara dual 48MP, chip A16 Bionic, USB-C, Dynamic Island.",
        image: "/images/imagenes_de_celulares/iphone13azul.jpeg",
        price: 650000,
        storage: "128GB",
        battery: "100%",
        color: "blue",
        brand: "Apple",
        alt: "iPhone 13",
        link: "#",
      },
      {
        id: "iphone-7",
        title: "iPhone 13",
        description:
          "Pantalla OLED Super Retina XDR 6.1'', cámara triple 48MP, chip A16 Bionic, USB-C, Dynamic Island.",
        image: "/images/imagenes_de_celulares/iphone13rosa.jpeg",
        price: 750000,
        storage: "128GB",
        battery: "100%",
        color: "pink",
        brand: "Apple",
        alt: "iPhone 13",
        link: "#",
      },
      {
        id: "iphone-8",
        title: "iPhone 13pro",
        description:
          "Pantalla OLED Super Retina XDR 6.1'', cámara dual 48MP, chip A16 Bionic, USB-C, Dynamic Island.",
        image: "/images/imagenes_de_celulares/iphone13pro.jpeg",
        price: 800000,
        storage: "128GB",
        battery: "100%",
        color: "white",
        brand: "Apple",
        alt: "iPhone 13",
        link: "#",
      },
      {
        id: "iphone-9",
        title: "iPhone 13pro-Max ",
        description:
          "Pantalla OLED Super Retina XDR 6.7'', cámara triple 48MP, chip A16 Bionic, USB-C, Dynamic Island.",
        image: "/images/imagenes_de_celulares/iphone13proMax-gris.jpeg",
        price: 850000,
        storage: "128GB",
        battery: "100%",
        color: "gray",
        brand: "Apple",
        alt: "iPhone 13",
        link: "#",
      },
      {
        id: "iphone-10",
        title: "iPhone 13pro-Max ",
        description:
          "Pantalla OLED Super Retina XDR 6.7'', cámara triple 48MP, chip A16 Bionic, USB-C, Dynamic Island.",
        image: "/images/imagenes_de_celulares/iphone13proMax.jpeg",
        price: 850000,
        storage: "128GB",
        battery: "100%",
        color: "black",
        brand: "Apple",
        alt: "iPhone 13",
        link: "#",
      },
      {
        id: "iphone-11",
        title: "iPhone 14pro",
        description:
          "Pantalla OLED Super Retina XDR 6.1'', cámara triple 48MP, chip A16 Bionic, USB-C, Dynamic Island.",
        image: "/images/imagenes_de_celulares/iphone14pro.jpeg",
        price: 900000,
        storage: "128GB",
        battery: "100%",
        color: "black",
        brand: "Apple",
        alt: "iPhone 14pro",
        link: "#",
      },
      {
        id: "iphone-12",
        title: "iPhone 15",
        description:
          "Pantalla OLED Super Retina XDR 6.1'', cámara dual 48MP, chip A16 Bionic, USB-C, Dynamic Island.",
        image: "/images/imagenes_de_celulares/iphone15.jpeg",
        price: 950000,
        storage: "128GB",
        battery: "100%",
        color: "black",
        brand: "Apple",
        alt: "iPhone 15",
        link: "#",
      },
      {
        id: "iphone-13",
        title: "iPhone 16",
        description:
          "Pantalla OLED Super Retina XDR 6.1'', cámara dual 48MP, chip A17 Pro, USB-C, Dynamic Island.",
        image: "/images/imagenes_de_celulares/iphone16.jpeg",
        price: 1400000,
        storage: "128GB",
        battery: "100%",
        color: "black",
        brand: "Apple",
        alt: "iPhone 16",
        link: "#",
      },
    ],
  },
  {
    brand: "Samsung",
    models: [
      {
        id: "samsung-1",
        title: "Samsung S24 ultra",
        description:
          "Pantalla Super AMOLED 6.5'' FHD+, cámara cuádruple de 64MP, batería de 4500mAh, Snapdragon 720G.",
        image: "/images/imagenes_de_celulares/SamsungS24Ultra.jpeg",
        price: 1400000,
        ram: "12GB",
        color: "grayligh",
        storage: "512GB",
        brand: "Samsung",
        alt: "Samsung S 24 ultra",
        link: "#",
      },
      {
        id: "samsung-2",
        title: "Samsung S24 FE",
        description:
          "Pantalla Super AMOLED 6.5'' FHD+, cámara cuádruple de 64MP, batería de 4500mAh, Snapdragon 720G.",
        image: "/images/imagenes_de_celulares/samsungS24FE.jpeg",
        price: 650000,
        ram: "8GB",
        storage: "256GB",
        color: "blueligh",
        brand: "Samsung",
        alt: "Samsung S 24 FE",
        link: "#",
      },
      {
        id: "samsung-3",
        title: "Samsung S23 plus",
        description:
          "Pantalla Super AMOLED 6.5'' FHD+, cámara cuádruple de 64MP, batería de 4500mAh, Snapdragon 720G.",
        image: "/images/imagenes_de_celulares/samsungS23plus.jpeg",
        price: 1200000,
        ram: "12GB",
        storage: "256GB",
        color: "white",
        brand: "Samsung",
        alt: "Samsung S 23 plus",
        link: "#",
      },
      {
        id: "samsung-4",
        title: "Samsung S21",
        description:
          "Pantalla Super AMOLED 6.5'' FHD+, cámara cuádruple de 64MP, batería de 4500mAh, Snapdragon 720G.",
        image: "/images/imagenes_de_celulares/SamsungS21.jpeg",
        price: 600000,
        ram: "8GB",
        storage: "256GB",
        color: "black",
        brand: "Samsung",
        alt: "Samsung S21",
        link: "#",
      },
      {
        id: "samsung-5",
        title: "Samsung Galaxy A52",
        description:
          "Pantalla Super AMOLED 6.5'' FHD+, cámara cuádruple de 64MP, batería de 4500mAh, Snapdragon 720G.",
        image: "/images/imagenes_de_celulares/Samsung-A52.jpeg",
        price: 200000,
        ram: "6GB",
        storage: "128GB",
        color: "black",
        brand: "Samsung",
        alt: "Samsung Galaxy A52",
        link: "#",
      },
      {
        id: "samsung-6",
        title: "Samsung Galaxy A25",
        description:
          "Pantalla AMOLED 6.4'' FHD+, cámara triple 50MP, batería 5000mAh, procesador MediaTek Helio G80.",
        image: "/images/imagenes_de_celulares/SamsumsugA-25.jpeg",
        price: 270000,
        ram: "8GB",
        storage: "256GB",
        color: "darkblue",
        brand: "Samsung",
        alt: "Samsung Galaxy A25",
        link: "#",
      },
      {
        id: "samsung-7",
        title: "Samsung Galaxy A22 5g",
        description:
          "Pantalla Super AMOLED 6.4'' HD+, cámara cuádruple 48MP, batería 5000mAh, procesador MediaTek Helio G80.5g",
        image: "/images/imagenes_de_celulares/SamsungA-22 5g.jpeg",
        price: 160000,
        ram: "4GB",
        storage: "64GB",
        color: "black",
        brand: "Samsung",
        alt: "Samsung Galaxy A22",
        link: "#",
      },
      {
        id: "samsung-8",
        title: "Samsung Galaxy A16",
        description:
          "Pantalla PLS LCD 6.5'', cámara triple 50MP, batería 5000mAh, procesador MediaTek Helio G80.",
        image: "/images/imagenes_de_celulares/Samsung-A16.jpeg",
        price: 280000,
        ram: "4GB",
        storage: "64GB",
        color: "darkblue",
        brand: "Samsung",
        alt: "Samsung Galaxy A16",
        link: "#",
      },
      {
        id: "samsung-9",
        title: "Samsung Galaxy A15",
        description:
          "Pantalla PLS LCD 6.4'', cámara triple 48MP, batería 5000mAh, procesador Exynos 850.",
        image: "/images/imagenes_de_celulares/samsung-A15.jpg",
        price: 240000,
        ram: "4GB",
        storage: "128GB",
        color: "white",
        brand: "Samsung",
        alt: "Samsung Galaxy A15",
        link: "#",
      },
      {
        id: "samsung-10",
        title: "Samsung Galaxy A14",
        description:
          "Pantalla PLS LCD 6.6'' FHD+, cámara triple 50MP, batería 5000mAh, procesador Exynos 850.",
        image: "/images/imagenes_de_celulares/SamsungA-14.jpeg",
        price: 170000,
        ram: "4GB",
        storage: "128GB",
        color: "black",
        brand: "Samsung",
        alt: "Samsung Galaxy A14",
        link: "#",
      },
      {
        id: "samsung-11",
        title: "Samsung Galaxy A13",
        description:
          "Pantalla PLS LCD 6.6'', cámara cuádruple 50MP, batería 5000mAh, procesador Exynos 850.",
        image: "/images/imagenes_de_celulares/SamsungA-13.jpeg",
        price: 150000,
        ram: "4GB",
        storage: "128GB",
        color: "blueligh",
        brand: "Samsung",
        alt: "Samsung Galaxy A13",
        link: "#",
      },
      {
        id: "samsung-12",
        title: "Samsung Galaxy A12",
        description:
          "Pantalla PLS LCD 6.5'', cámara cuádruple 48MP, batería 5000mAh, procesador MediaTek Helio P35.",
        image: "/images/imagenes_de_celulares/Samsung-A12.jpeg",
        price: 150000,
        ram: "4GB",
        storage: "128GB",
        color: "black",
        brand: "Samsung",
        alt: "Samsung Galaxy A12",
        link: "#",
      },
      {
        id: "samsung-13",
        title: "Samsung Galaxy A06",
        description:
          "Pantalla PLS LCD 6.1'', cámara simple 8MP, batería 3000mAh, procesador Exynos 7884.",
        image: "/images/imagenes_de_celulares/SamsungA-06.jpeg",
        price: 170000,
        ram: "3GB",
        storage: "32GB",
        color: "darkblue",
        brand: "Samsung",
        alt: "Samsung Galaxy A06",
        link: "#",
      },
      {
        id: "samsung-14",
        title: "Samsung Galaxy A05",
        description:
          "Pantalla PLS LCD 6.5'', cámara dual 13MP, batería 5000mAh, procesador Unisoc SC9863A.",
        image: "/images/imagenes_de_celulares/Samsung-A05.jpeg",
        price: 160000,
        ram: "4GB",
        storage: "128GB",
        color: "darkblue",
        brand: "Samsung",
        alt: "Samsung Galaxy A05",
        link: "#",
      },
      {
        id: "samsung-15",
        title: "Samsung Galaxy A03",
        description:
          "Pantalla PLS LCD 6.5'', cámara dual 48MP, batería 5000mAh, procesador Unisoc T606.",
        image: "/images/imagenes_de_celulares/Samsung-A03.jpeg",
        price: 120000,
        ram: "4GB",
        storage: "64GB",
        color: "black",
        brand: "Samsung",
        alt: "Samsung Galaxy A03",
        link: "#",
      },
      {
        id: "samsung-16",
        title: "Samsung Galaxy A03 Core",
        description:
          "Pantalla PLS LCD 6.5'', cámara simple 8MP, batería 5000mAh, procesador Unisoc SC9863A.",
        image: "/images/imagenes_de_celulares/Samsung-A03Core.jpeg",
        price: 100000,
        ram: "2GB",
        storage: "32GB",
        color: "greenligh",
        brand: "Samsung",
        alt: "Samsung Galaxy A03 Core",
        link: "#",
      },
    ],
  },
  {
    brand: "Motorola",
    models: [
      {
        id: "motorola-1",
        title: "Motorola E22i",
        description:
          "Pantalla IPS LCD 6.5'', cámara principal 16MP, batería 4000mAh, procesador Unisoc T606.",
        image: "/images/imagenes_de_celulares/MotorolaE-22i.jpeg",
        price: 110000,
        ram: "4GB",
        storage: "64GB",
        color: "graydark",
        brand: "Motorola",
        alt: "Motorola E22i",
        link: "#",
      },
      {
        id: "motorola-2",
        title: "Motorola E22",
        description:
          "Pantalla IPS LCD 6.5'', cámara principal 16MP, batería 4000mAh, procesador Unisoc T606.",
        image: "/images/imagenes_de_celulares/Motorola-E22.jpeg",
        price: 150000,
        ram: "4GB",
        storage: "128GB",
        color: "graydark",
        brand: "Motorola",
        alt: "Motorola E22",
        link: "#",
      },
      {
        id: "motorola-3",
        title: "Motorola G14",
        description:
          "Pantalla IPS LCD 6.5'', cámara principal 50MP, batería 5000mAh, procesador MediaTek Helio G37.",
        image: "/images/imagenes_de_celulares/Motorola-G14gris.jpeg",
        price: 110000,
        ram: "4GB",
        storage: "64GB",
        color: "graydark",
        brand: "Motorola",
        alt: "Motorola G14",
        link: "#",
      },
      {
        id: "motorola-4",
        title: "Motorola G14",
        description:
          "Pantalla IPS LCD 6.5'' Full HD+, cámara principal 50MP, batería 5000mAh, procesador MediaTek Helio G37.",
        image: "/images/imagenes_de_celulares/Motorola-G14.jpeg",
        price: 160000,
        ram: "4GB",
        storage: "128GB",
        color: "blueligh",
        brand: "Motorola",
        alt: "Motorola G14",
        link: "#",
      },
      {
        id: "motorola-5",
        title: "Motorola G30",
        description:
          "Pantalla IPS LCD 6.5'', cámara cuádruple 64MP, batería 5000mAh, procesador Snapdragon 662.",
        image: "/images/imagenes_de_celulares/Motorola-G30.jpeg",
        price: 120000,
        ram: "4GB",
        storage: "128GB",
        color: "violet",
        brand: "Motorola",
        alt: "Motorola G30",
        link: "#",
      },
      {
        id: "motorola-6",
        title: "Motorola G53",
        description:
          "Pantalla IPS LCD 6.5'' FHD+ 120Hz, cámara principal 50MP, batería 5000mAh, procesador MediaTek Dimensity 920.",
        image: "/images/imagenes_de_celulares/Motorola-G53.jpeg",
        price: 190000,
        ram: "4GB",
        storage: "128GB",
        color: "bluedark",
        brand: "Motorola",
        alt: "Motorola G53",
        link: "#",
      },
      {
        id: "motorola-7",
        title: "Motorola G54",
        description:
          "Pantalla IPS LCD 6.5'' FHD+ 120Hz, cámara principal 50MP, batería 5000mAh, procesador MediaTek Dimensity 930.",
        image: "/images/imagenes_de_celulares/Motorola-G54.jpeg",
        price: 200000,
        ram: "8GB",
        storage: "256GB",
        color: "bluedark",
        brand: "Motorola",
        alt: "Motorola G54",
        link: "#",
      },
      {
        id: "motorola-8",
        title: "Motorola G54",
        description:
          "Pantalla IPS LCD 6.5'' FHD+ 120Hz, cámara principal 50MP, batería 5000mAh, procesador MediaTek Dimensity 930 color verde.",
        image: "/images/imagenes_de_celulares/Motorola-G54.jpeg",
        price: 200000,
        ram: "8GB",
        storage: "256GB",
        color: "greenligth",
        brand: "Motorola",
        alt: "Motorola G54",
        link: "#",
      },
      {
        id: "motorola-9",
        title: "Motorola G9 Power",
        description:
          "Pantalla IPS LCD 6.8'', cámara triple 64MP, batería gigante 6000mAh, procesador Snapdragon 662.",
        image: "/images/imagenes_de_celulares/MotorolaG-9power.jpeg",
        price: 140000,
        ram: "4GB",
        storage: "128GB",
        color: "green",
        brand: "Motorola",
        alt: "Motorola G9 Power",
        link: "#",
      },
      {
        id: "motorola-10",
        title: "Motorola G200",
        description:
          "Pantalla IPS LCD 6.8'' 120Hz, cámara triple 108MP, batería 6000mAh, procesador Snapdragon 732G.",
        image: "/images/imagenes_de_celulares/MotorolaG200.jpeg",
        price: 250000,
        ram: "8GB",
        storage: "128GB",
        color: "blue",
        brand: "Motorola",
        alt: "Motorola G200",
        link: "#",
      },
    ],
  },

  {
    brand: "Xiaomi",
    models: [
      {
        id: "xiaomi-1",
        title: "Xiaomi Redmi 14C",
        description:
          "Pantalla IPS LCD 6.53'', cámara dual 50MP, batería 5000mAh, procesador MediaTek Helio G88.",
        image: "/images/imagenes_de_celulares/Redmi14-C.jpeg",
        price: 200000,
        ram: "8GB",
        storage: "256GB",
        color: "green",
        brand: "Xiaomi",
        alt: "Redmi 14C",
        link: "#",
      },
      {
        id: "xiaomi-2",
        title: "Xiaomi Note 10S",
        description:
          "Pantalla AMOLED 6.47'', cámara cuádruple 64MP, batería 4780mAh, procesador MediaTek Helio G95.",
        image: "/images/imagenes_de_celulares/RedmiNote-10s.jpeg",
        price: 170000,
        ram: "6GB",
        storage: "128GB",
        color: "bluedark",
        brand: "Xiaomi",
        alt: "Xiaomi Note 10S",
        link: "#",
      },
      {
        id: "xiaomi-3",
        title: "Xiaomi Note 11 Pro",
        description:
          "Pantalla AMOLED 6.67'' 120Hz, cámara cuádruple 108MP, batería 5000mAh, procesador MediaTek Dimensity 920.",
        image: "/images/imagenes_de_celulares/RedmiNote-11pro.jpeg",
        price: 200000,
        ram: "6GB",
        storage: "128GB",
        color: "turquoise",
        brand: "Xiaomi",
        alt: "Xiaomi Note 11 Pro",
        link: "#",
      },
      {
        id: "xiaomi-4",
        title: "Xiaomi Note 9S",
        description:
          "Pantalla IPS LCD 6.67'', cámara cuádruple 48MP, batería 5020mAh, procesador Snapdragon 720G.",
        image: "/images/imagenes_de_celulares/RedmiNote-9s.jpeg",
        price: 140000,
        ram: "4GB",
        storage: "128GB",
        color: "bluedark",
        brand: "Xiaomi",
        alt: "Xiaomi Note 9S",
        link: "#",
      },
    ],
  },
  {
    brand: "Honor",
    models: [
      {
        id: "Honor-1",
        title: "Honor Magic 6 lite",
        description:
          "Pantalla AMOLED 6.38'', cámara dual 48MP, batería 4000mAh, procesador MediaTek Helio G80.",
        image: "/images/imagenes_de_celulares/HonorMagic6lite.jpeg",
        price: 190000,
        ram: "8GB",
        storage: "256GB",
        color: "greendark",
        brand: "Honor",
        alt: "Honor Magic 6 lite",
        link: "#",
      },
    ],
  },
  {
    brand: "vivo",
    models: [
      {
        id: "vivo-1",
        title: "Vivo Y7s",
        description:
          "Pantalla AMOLED 6.38'', cámara dual 48MP, batería 4000mAh, procesador MediaTek Helio G80.",
        image: "/images/imagenes_de_celulares/VivoY-7s.jpeg",
        price: 180000,
        ram: "6GB",
        storage: "128GB",
        color: "greenlight",
        brand: "Vivo",
        alt: "Vivo Y7s",
        link: "#",
      },
    ],
  },
  {
    brand: "TECNO",
    models: [
      {
        id: "Tecno-1",
        title: "Tecno Spark 20",
        description:
          "Pantalla AMOLED 6.38'', cámara dual 48MP, batería 4000mAh, procesador MediaTek Helio G80.",
        image: "/images/imagenes_de_celulares/TecnoSpark20.jpeg",
        price: 190000,
        ram: "8GB",
        storage: "256GB",
        color: "white",
        brand: "TECNO",
        alt: "TECNO",
        link: "#",
      },
    ],
  },
  {
    brand: "phone basic",
    models: [
      {
        id: "basic-1",
        title: "Nokia 106",
        description:
          "Teléfono básico con pantalla LCD 1.8'', batería de larga duración, radio FM y linterna integrada.",
        image: "/images/imagenes_de_celulares/nokia-106.jpeg",
        price: 50000,
        ram: "2GB",
        storage: "32GB",
        color: "black",
        brand: "Nokia",
        alt: "Nokia 106",
        link: "#",
      },
      {
        id: "basic-2",
        title: "LG B220",
        description:
          "Teléfono simple con pantalla LCD 2.4'', teclado físico, radio FM y batería de larga duración.",
        image: "/images/imagenes_de_celulares/LG b220.jpeg",
        price: 65000,
        ram: "2GB",
        storage: "32GB",
        color: "blue",
        brand: "LG",
        alt: "LG B220",
        link: "#",
      },
      {
        id: "basic-3",
        title: "MiniSmartphone",
        description:
          "Smartphone compacto con pantalla 3.5'', almacenamiento básico, cámara simple y batería pequeña.",
        image: "/images/imagenes_de_celulares/telefonito.jpeg",
        price: 90000,
        ram: "2GB",
        storage: "8GB",
        color: "black",
        brand: "Soyes",
        alt: "MiniSmartphone",
        link: "#",
      },
    ],
  },
];
